### ISSUE TITLE
interval_ok is unbound at 310: APPS/gathertw.sh

### ISSUE THREAD

**Issue by isaomatsunami** [ShellShoccar-jpn/kotoriotoko#10]
日本語で失礼します。
MacOSでgathertw.shを実行すると、310行目でinterval_ok: unbound variableになりました。
当座の処置として、315行目を310の直前に移動させて実行させています。
Mac OS固有の問題でしょうか？

**Comment by colrichie** [comment]
その指摘と対処方法はどちらも正しい。手間を取らせてしまって済まない。
今から直ちに、ソースコードの修正を行うことにする。そして、指摘してくれてありがとう。

**Comment by isaomatsunami** [comment]
素晴らしいライブラリをありがとうございます。この記事のこの部分で利用させていただきました。
https://static.chunichi.co.jp/chunichi/pages/feature/election/measuring_unmeasurable.html#autocall
