### ISSUE TITLE
stwsrch.sh: API error: Error 401 Unauthorized

### ISSUE THREAD

**Issue by hillz2** [ShellShoccar-jpn/kotoriotoko#5]
Trying to fix this one:
```
root@AngelBeats:/mnt/usb2/kotoriotoko/BIN# ./stwsrch.sh indonesia
The 1st response has arrived...
stwsrch.sh: API error: Error 401 Unauthorized
```

**Comment by richmikan** [comment]
I have two qestions I ask to you.

Question 1:

By which way did you generate your access keys?
a. by getstarted.sh command
b. by [Twitter Apps website](https://apps.twitter.com/)

If you did by "b", make sure that your application has the full permission "Read, Write and Access direct messages".


Question 2:

Don't you use stwsrch.sh too much freqently? If you so, wait in more over 15 minutes.

Or are there some curl processes on the background? If it so, run `killall curl` and wait in more over 15 minutes.

**Comment by hillz2** [comment]
I tried bot options **a** and **b** they don't work, I still get the same error. My app has a full permission https://s23.postimg.org/mhrslvh7f/screenshot-2017-07-21_15-38-50.png

I don't use stwsrch.sh too often, I've tried waiting for 30 minutes before executing the script again but it still gives me the same error, the weird thing is that it works just fine on manjaro with the same key that is on my openwrt.

**Comment by richmikan** [comment]
Umm.. That seems a little difficult.

Please let me know the arguments of your curl command works on stwsrch.sh with the following command (But you should hide the string of your keys)

```
* While you run stwsrch.sh
$ ps w | grep curl
```

And I want to know what the curl command send to STDOUT. To know that, type the following and let me know the file.

```
$ ./stwsrch.sh --rawout=FOO.txt KEYWORD
```

**Comment by hillz2** [comment]
The script exits immediately so I can't execute `ps w | grep curl` while running stwsrch.sh. Here's the output of `FOO.txt`:
```
<html>\n<head>\n<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>\n<title>Error 401 Unauthorized</title>
</head>
<body>
<h2>HTTP ERROR: 401</h2>
<p>Problem accessing '/1.1/statuses/filter.json'. Reason:
<pre>    Unauthorized</pre>
</body>
</html>
```
Let me know how I can capture the curl command completely

**Comment by richmikan** [comment]
Thanks. But will you please try again with the following step?

## To confirm the argument of curl,

1)  Replace line 495 into the following.

```
} 3>&2 2>/tmp/FOO.log &   # Ignore job exiting message
↓
} 3>&2 2>/dev/null &           # Ignore job exiting message
```

2) Run by the following command.

```
$ sh -x ./stwsrch.sh KEYWORD
```

3) Hide your secret key in the logfile.

4) Report FOO.log to me because the argument has been written in the file.

**Comment by hillz2** [comment]
https://pastebin.com/axcy0AeZ

**Comment by richmikan** [comment]
Thanks.

```
+ curl -s -H Authorization: OAuth oauth_consumer_key=xxxxxxxxxxxxxxxxxxxxxx,oauth_nonce=xxxxxxxxxxxxxxxxxxxxxx,oauth_signature=xxxx,oauth_signature_method=HMAC-SHA1,oauth_timestamp=1500655766,oauth_token=xxxxxxxxxxxxxxxxxxxxxx,oauth_version=1.0,track=KEYWORD -d track=KEYWORD https://stream.twitter.com/1.1/statuses/filter.json
```

The value of oauth_timestamp seems not accurate. The timestamp "1500655766" means "2017-07-21 16:49:26 (UTC)". I recommend you to adjust your host's clock before accessing.

**Comment by hillz2** [comment]
Right now:
```
root@AngelBeats:~# date 
Fri Jul 21 17:15:39 UTC 2017
```
It's the correct time in indonesia (UTC+7) How should I adjust it ?

**Comment by richmikan** [comment]
Sorry I didn't know whether the time you showed was accurate nor not because I'm in Japan, which is a diffrent time zone from yours. But Twitter authentication requires us accurate timestamp (within a few minutes). So I have been denied an old OAuth string which I generated several minutes ago.

**Comment by richmikan** [comment]
Please make sure the your stwsrch.sh is completely same as mine.

```
$ wget https://raw.githubusercontent.com/ShellShoccar-jpn/kotoriotoko/master/BIN/stwsrch.sh
$ chmod +x stwsrch.sh
$ md5sum stwsrch.sh
cda138f9644b9df9e63f569c97e51bc1  stwsrch.sh
```

**Comment by richmikan** [comment]
After all the cause is the wrong timestamp!

You have to adjust your hosts clock to, for example, [this](http://www.worldtimeserver.com/current_time_in_UTC.aspx).

**Comment by hillz2** [comment]
I fixed it. It was my openwrt's fault. I had to change the timezone at `/etc/config/system` and then restart it with `/etc/init.d/system restart`. Previously it was like this:
```
config system                                   
        option timezone 'UTC'                 
        option hostname 'AngelBeats'            

config timeserver 'ntp'                         
        list server '0.openwrt.pool.ntp.org'    
        list server '1.openwrt.pool.ntp.org'    
        list server '2.openwrt.pool.ntp.org'    
        list server '3.openwrt.pool.ntp.org'    
        option enabled '1'                      
        option enable_server '0'                
```
The correct one should be like this:
```
config system                                   
        option timezone 'WIT-7'                 
        option hostname 'AngelBeats'            

config timeserver 'ntp'                         
        list server '0.openwrt.pool.ntp.org'    
        list server '1.openwrt.pool.ntp.org'    
        list server '2.openwrt.pool.ntp.org'    
        list server '3.openwrt.pool.ntp.org'    
        option enabled '1'                      
        option enable_server '0'                
```
I'm sorry for taking your time and thank you for helping me.

**Comment by hillz2** [comment]
You can take a look at the timezone table at https://wiki.openwrt.org/doc/uci/system#time_zones

**Comment by richmikan** [comment]
Good, I'm also happy because the cause is not a kotoriotoko's bug.

Enjoy!
