### ISSUE TITLE
Suggestion: Ability to filter out replied users.

### ISSUE THREAD

**Issue by BillZoro** [ShellShoccar-jpn/kotoriotoko#7]
Quick note, love kotoriotoko, been using it for months now.

But i came across a little problem, i want to make an auto-shoutout system, that if someone tags me they get a retweet on that specific tweet.

However everytime i use "twsrch.sh @myuser" it returns any tweets that contains @myuser, which includes any and all replies users do on any tweet or retweet i've made, and of course i can't just retweet all of them.

So an option to remove the replied users as part of the message would be great.

**Comment by 321516** [comment]
Hi, thank you for using kotoriotoko. I'm glad you liked it.

Of course, I'd like to help you, but I unfortunately don't understand your request enough yet.

> remove the replied users as part of the message

Tell me more in detail, which tweet should be removed and which tweet should be remained.

**Comment by BillZoro** [comment]
Thanks for responding! I still struggle with english, so my sentences can be confusing sometimes.

When i use "twsrch.sh @myUser" i get comments returned like:

"@myUser yeah, that's what i'm talkin about"
"Going online right now! @myUser @anotherUser @otherUser"

The first one actually is someone commenting on a thread on any of my tweets or retweets, the second one is someone tagging me.
I'd like a way to remove from the searchs the first one, tweets on a comment thread, and keep the second one, tweets which someone tagged me.

Images to help understand.
![c1](https://user-images.githubusercontent.com/37717821/57982348-84f68e80-7a1a-11e9-9396-c3052b039381.png)
![c2](https://user-images.githubusercontent.com/37717821/57982347-845df800-7a1a-11e9-8a95-fb0013678130.png)

You can clearly see which one is which on twitter, of course. But kotoriotoko grabs both of them as a result if i use "twsrch.sh @StrongAnvil"

**Comment by 321516** [comment]
Umm, I'm sorry but I can't understand what you'd like to do for your auto-shoutout system yet.

Which one is what you want to do to make your auto-shoutout system?
a. collecting tweet-IDs for replying or retweeting
b. collecting screen names (like @foo) to post a tweet having the name as a mention.

In other words, when "twsrch.sh @StrongAnvil" gives you the 2 tweets,
* [https://twitter.com/Txno__/status/1129882628574851072](https://twitter.com/Txno__/status/1129882628574851072)
* [https://twitter.com/Flux31780558/status/1129863518835105798](https://twitter.com/Flux31780558/status/1129863518835105798)

which part do you like to pick up from the tweets?

Let me know the objects (tweet-id, screen-name, so forth) you'd like to pick up from the above example and also so let me why the objects are chosen?

e.g.
* 1129863518835105798 (because the tweet isn't a replying one)
* @StrongAnvil, @thegerbilarmy (because these names are in a tweet which isn't a reply)

**Comment by BillZoro** [comment]
I made a system which can get the tweet id from these tweets, but i don't have a way (or don't know how to) to filter comments which are a reply.

What i suggested is a filter for kotoriotoko to filter comments from a reply thread, while keeping the others.

Because when i use "twsrch.sh @StrongAnvil" i want to filter comments from a reply and only keep those that actually mention me.

**Comment by 321516** [comment]
Perhaps, Twitter advanced search commands could help you, couldn't it?

A Example of Query: "@StrongAnvil -from:StrongAnvil"

The above query means search tweets contains "@StrongAnvil" but which doesn't contain tweets which @StrongAnvil tweeted.

So, you can inquire with the following command:
"`twsrch.sh '@StrongAnvil -from:StrongAnvil'`"

See more in detail for the advanced search: [Using standard search — Twitter Developers](https://developer.twitter.com/en/docs/tweets/search/guides/standard-operators.html)

If the advanced commands can't help you yet, please ask me again.

**Comment by BillZoro** [comment]
I'm confused.
twsrch.sh '@StrongAnvil to:StrongAnvil' only returns tweets that contains "@StrongAnvil" as the very first word.

Your example:
twsrch.sh '@StrongAnvil -to:StrongAnvil'" actually filtered most of it, but still returns a few unwanted tweets, for example, it still returns replies from retweets i did. 
I guess that's because the original poster gets tagged as the one who is being replied, not me.

Like this one for example: https://twitter.com/i/web/status/1130459863190949889

Also thanks for the link, i didn't know about these.

**Comment by BillZoro** [comment]
Yeah, using "-to:StrongAnvil" returns tweets if @StrongAnvil isn't the exact very first word, "to:StrongAnvil" does the opposite and returns tweets where @StrongAnvil is the exact first word. In short they don't do much.

This page doesn't cite them, but there's actually more filters, i've been using filter:replies and filter:mentions which do exactly what i want. Thanks for pointing me to it, thanks for all the help!

**Comment by 321516** [comment]
I was only able to give you a hint to help you, but you finally got the solution by your penetrating insight. I'm glad you can do it!

**Comment by BillZoro** [comment]
Hi, thanks for all the help, i'm sorry if somehow my comments came off as bad in any way, that wasn't my intention, i'm not very good at english and sometimes i can't translate my intentions well enough.

**Comment by 321516** [comment]
No problem. Thank you for asking. It will help kotoriotoko greater.
